### ISSUE TITLE
Documents in Download Center, Activity "Assessment", Moodle 3.9

### ISSUE THREAD

**Issue by eLearning-Group** [academic-moodle-cooperation/moodle-local_downloadcenter#25]
I noticed today that documents of the activity "Task" are visible in the Download Center, even if they are not yet visible in the task itself, because the corresponding deadline has not been reached yet. The documents remain hidden only when the whole activity is set to "hidden".

Since we set up exams this way and don't always want to set the check to "show" before the exam, because we often have several exams at the same time, it would be important if the documents are also only visible in the Download Center at the time of the exam (=start of submission) when "Always show description" is deactivated.

sorry because of my english....

**Comment by goggo24** [comment]
Thanks for reporting. We were able to recreate the bug and are already working on it. Eva

**Comment by mkemmerling** [comment]
Fixed with versions 3.9.1 and 3.10.1.

**Comment by eLearning-Group** [comment]
We have version 3.9.5 and it is still a problem there. Sorry and it is not the activity "test". It is the activity "Assignment" (Aktivität "Aufgabe" in Deutsch)

**Comment by goggo24** [comment]
We just published the newest version - do you have already checked out donwloadcenter v.3.9.1?

**Comment by eLearning-Group** [comment]
Thanks a lot... that's the problem, we have Downloadcenter version 3.9.0
